### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by JCLaHoot** [danielrob/stockify#1]
For some reason Photoshop isn't on my laptop at the moment, but I'll try to describe without that... 
- I don't think the checks and Xs should be coloured unless it's for the image that's selected, and they should be in grayscale for the other images 
- The checkbox, when coloured, should be green, or some other affirmative colour. An overly simplified breakdown of how people perceive visuals is, in order: colour -> shapes -> images -> text. So colour is the first thing that someone will see. A red check can also sometimes indicate an error.

-by default, if an image is selected and neither the check or the X are selected for that image, both of these symbols should appear, but only a shade lighter or darker than the background colour. when the user selects whether to pick it or reject it, then whichever one they pick/reject will become coloured to indicate that it's selected. This way, when a user goes to import some images, but hasn't picked or rejected any, the feature won't be completely hidden.

-it also wasn't immediately evident how to pick/reject an image if I didn't know the key mapping.

**Comment by danielrob** [comment]
Thanks for the feedback, interest, and suggestions! (I'd had similar thoughts, but not nearly as well described).

The suggested changes (as interpreted/inspired) are sitting in the [pickRejectColors](https://github.com/danielrob/stockify/tree/pickRejectColors) branch, and/or you can download [Stockify-darwin-x64-pickRejectColors.zip](https://s3-ap-southeast-2.amazonaws.com/iem9b5snbg8n-static-host/Stockify-darwin-x64-pickRejectColors.zip) or [Stockify-win32-x64-pickRejectColors.zip](https://s3-ap-southeast-2.amazonaws.com/iem9b5snbg8n-static-host/Stockify-win32-x64-pickRejectColors.zip) to view the changes. I've also added click-to-pick/reject. 

Let me know what you think?

**Comment by danielrob** [comment]
I merged the changes, so just use master branch.
